package com.aptota.app.model;
// Generated Apr 11, 2020 9:22:27 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemType generated by hbm2java
 */
@Entity
@Table(name = "item_type", catalog = "restaurent_erp")
public class ItemType implements java.io.Serializable {

	private Integer iditemType;
	private String typeName;
	private String description;

	public ItemType() {
	}

	public ItemType(String typeName, String description) {
		this.typeName = typeName;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iditem_type", unique = true, nullable = false)
	public Integer getIditemType() {
		return this.iditemType;
	}

	public void setIditemType(Integer iditemType) {
		this.iditemType = iditemType;
	}

	@Column(name = "type_name", length = 45)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
