package com.aptota.app.model;
// Generated Apr 11, 2020 9:22:27 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "restaurent_erp")
public class Item implements java.io.Serializable {

	private Integer iditem;
	private String itemCode;
	private String itemDescription;
	private Integer itemTypeId;
	private String itemName;
	private Double itemPrice;

	public Item() {
	}

	public Item(String itemCode, String itemDescription, Integer itemTypeId, String itemName, Double itemPrice) {
		this.itemCode = itemCode;
		this.itemDescription = itemDescription;
		this.itemTypeId = itemTypeId;
		this.itemName = itemName;
		this.itemPrice = itemPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iditem", unique = true, nullable = false)
	public Integer getIditem() {
		return this.iditem;
	}

	public void setIditem(Integer iditem) {
		this.iditem = iditem;
	}

	@Column(name = "item_code", length = 25)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "item_description")
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "item_type_id")
	public Integer getItemTypeId() {
		return this.itemTypeId;
	}

	public void setItemTypeId(Integer itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	@Column(name = "item_name", length = 20)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_price", precision = 22, scale = 0)
	public Double getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Double itemPrice) {
		this.itemPrice = itemPrice;
	}

}
