package com.aptota.app.model;
// Generated Apr 11, 2020 9:22:27 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RestaurentTable generated by hbm2java
 */
@Entity
@Table(name = "restaurent_table", catalog = "restaurent_erp")
public class RestaurentTable implements java.io.Serializable {

	private Integer idtable;
	private String tableName;
	private String status;

	public RestaurentTable() {
	}

	public RestaurentTable(String tableName, String status) {
		this.tableName = tableName;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtable", unique = true, nullable = false)
	public Integer getIdtable() {
		return this.idtable;
	}

	public void setIdtable(Integer idtable) {
		this.idtable = idtable;
	}

	@Column(name = "table_name", length = 45)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "status", length = 5)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
